title: Marika & Maciek
description: 14 sierpnia 2019
host: 0.0.0.0

url: https://marikaimaciek.starsquare.co.uk
baseurl: ""
repository: cmbuckley/marikaimaciek.pl

markdown: kramdown
highlighter: rouge

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

defaults:
  - scope:
      type: pages
    values:
      og_type: website

navigation:
 - title: Home
   url: /
 - title: Pare Słów
   url: /slow
 - title: Ślub
   url: /slub
 - title: Wesele
   url: /wesele
